export const trophies = {
    'Civil Rights': 'LIBERAL',
    'Economy': 'ECONOMY',
    'Political Freedoms': 'POLIFREE',
    'Population': 'POPULATION',
    'Wealth Gaps': 'WEALTHGAPS',
    'Death Rate': 'DEATH',
    'Compassion': 'COMPASSIONATE',
    'Eco Friendliness': 'ECO-GOVT',
    'Social Conservatism': 'CONSERVATIVE',
    'Nudity': 'NUDE',
    'Automobile Manufacturing': 'AUTO',
    'Cheese Exports': 'CHEESE',
    'Basket Weaving': 'BASKET',
    'Informtion Technology': '',
    'Pizza Delivery': 'PIZZA',
    'Trout Fishing': 'FISH',
    'Arms Manufacturing': 'ARMS',
    'Agriculture': 'AGRICULTURE',
    'Beverage Sales': 'SODA',
    'Timber Woodchipping': 'TIMBER',
    'Mining': 'MINING',
    'Insurance': 'INSURANCE',
    'Furniture Restoration': 'FURNITURE',
    'Retail': 'RETAIL',
    'Book Publishing': 'PUBLISHING',
    'Gambling': 'GAMBLING',
    'Manufacturing': 'MANUFACTURING',
    'Government Size': 'GOVT',
    'Welfare': 'WELFARE',
    'Public Healthcare': 'HEALTHCARE',
    'Law Enforcement': 'POLICE',
    'Business Subsidization': 'BUSINESS',
    'Religiousness': 'DEVOUT',
    'Income Equality': 'EQUALITY',
    'Niceness': 'NICE',
    'Rudeness': 'RUDE',
    'Intelligence': 'SMART',
    'Ignorance': 'STUPID',
    'Political Apathy': 'APATHETIC',
    'Health': 'HEALTHY',
    'Cheerfulness': 'HAPPY',
    'Weather': 'WEATHER',
    'Compliance': 'LOWCRIME',
    'Safety': 'SAFE',
    'Lifespan': 'LIFE',
    'Ideological Radicality': 'EXTREME',
    'Defense Forces': 'DEFENSE',
    'Pacifism': 'PEACE',
    'Economic Freedom': 'PRO-MARKET',
    'Taxation': 'HIGHTAX',
    'Freedom From Taxation': 'LOWTAX',
    'Corruption': 'CORRUPT',
    'Integrity': 'LEASTCORRUPT',
    'Authoritarianism': 'AUTHORITARIAN',
    'Youth Rebelliousness': 'REBELYOUTH',
    'Culture': 'CULTURE',
    'Employment': 'EMPLOYED',
    'Public Transport': 'PUBLICTRANSPORT',
    'Tourism': 'TOURISM',
    'Weaponization': 'ARMED',
    'Recreational Drug Use': 'DRUGS',
    'Obesity': 'FAT',
    'Secularism': 'GODFORSAKEN',
    'Environmental Beauty': 'ENVIRONMENT',
    'Charmlessness': 'AVOIDED',
    'Influence': 'INFLUENCE',
    'World Assembly Endorsements': 'ENDORSED',
    'Averageness': 'AVERAGE',
    'Human Development Index': 'HDI',
    'Primitiveness': 'PRIMITIVE',
    'Scientific Advancement': 'ADVANCED',
    'Inclusiveness': 'INCLUSIVE',
    'Average Income': '',
    'Average Income Of Poor': 'POORINCOME',
    'Average Income Of Rich': 'RICHINCOME',
    'Public Education': 'EDUCATED',
    'Economic Output': 'GDP',
    'Crime': 'CRIME',
    'Foreign Aid': 'AID',
    'Black Market': 'BLACKMARKET',
    'Residency': 'STATIONARY',
    'Average Disposable Income': 'DISPINCOME',
    'International Artwork': 'DECK',
    'Food Quality': 'FOODQUALITY',
    'Patriotism': 'PATRIOTISM'
};
